name: EmeraldSword
version: 1.0.0
main: dev.nicooo.emeraldsword.EmeraldSwordPlugin
api-version: 1.21
author: Nicooo23456
description: A plugin that adds a powerful Emerald Sword to Minecraft
commands:
  emeraldsword:
    description: Gives you the Emerald Sword
    usage: /emeraldsword
    permission: emeraldsword.give